:link-caketime: https://developer.amazon.com/en-US/docs/alexa/workshops/build-an-engaging-skill/get-started/index.html[Workshop: Build an Engaging Alexa Skill, window=_blank]
:link-quick-setup: link:quick-start.adoc[quick setup instructions, window=_blank]

= Welcome

{blank}

Welcome to How to Build a Multimodal Alexa Skill, a continuation of the deprecated Cake Time tutorial.  To use this tutorial, see the {link-quick-setup} to get the code and overview of the Cake Time Skill for use in this tutorial.  If you need to learn the basics of building a skill, refer to the new {link-caketime}.  After taking this course, you will have the information needed to create rich multimodal experiences for Alexa using Alexa Presentation Language (APL). The course will teach you the following:

* link:module1.adoc[Module 1]: Why Build Multimodal Alexa Skills?
* link:module2.adoc[Module 2]: Build Your First Visuals with the APL Authoring Tool
* link:module3.adoc[Module 3]: Modify Your Backend to Add LaunchRequest Visuals
* link:module4.adoc[Module 4]: Create More Visuals with Less
* link:module5.adoc[Module 5]: Add Animation and Video Control
* link:module6.adoc[Module 6]: Wrapping Up & Resources

== What is Cake Time?
The Cake Time course is an introductory skill building course where you can build a simple Alexa skill (Cake Time skill) which remembers your birthday. On repeated usage of the Cake Time skill, you'll either hear a Happy Birthday message from Alexa, or a countdown of days until it is your birthday. In this course, we are going to add visuals and animations to teach the fundamentals of https://developer.amazon.com/docs/alexa-presentation-language/understand-apl.html[building with APL, window=_blank]. If you are new to skill building, we recommend you check out the {link-caketime}, but if you are already building Alexa skills or are already familiar with the concepts, then keep reading! Code for the Cake Time skill and instructions to set the skill up will be provided later in the course if you need it.
